### ISSUE TITLE
Possibility to get the letter

### ISSUE THREAD

**Issue by stephane-r** [ArturKalach/react-native-external-keyboard#19]
Hi @ArturKalach 

Thank you for your great external keyboard menu. This is a pretty difficult topic on Android and I feel like it does the job fantastically ! Well done !

I have a question: why not include the letter (if letter) in addition to the keycode ? Is this wanted ? I'm going to see about making the modification on my side, but I'm surprised that the value is not there.

**Comment by ArturKalach** [comment]
Hello @stephane-r,
I have added unicode number and char info to the events in the last release `v0.2.6`. Could you check if it that what you expected?

<img width="541" alt="image" src="https://github.com/ArturKalach/react-native-external-keyboard/assets/112642862/a23feebe-a540-4352-a49f-587038c05c0d">

Thank you in advance.

**Comment by stephane-r** [comment]
Hey @ArturKalach :)

It look nice ! I had made the change locally for the Android part, but I'm not able to do it in iOS part ^^ Your Android part is much better than mine as well 😄

**Comment by ArturKalach** [comment]
Hello,

You could write your own wrapper for "Enter" and "Tab" based on key code, but I will duble check, and maybe add this functionality.
What I found, `unicode` has white space characters, but somewhy ios and android don't provide them by defatult.

<img width="1007" alt="image" src="https://github.com/ArturKalach/react-native-external-keyboard/assets/112642862/c9866592-e249-4ebe-915d-8eaf069c7124">

I will research different resources and try to add at least \t \n symbols.

**Comment by stephane-r** [comment]
Ok I see.

I'll try to do some tests during the day and I'll send you a PR on Android 😃

**Comment by ArturKalach** [comment]
Hello @stephane-r,
The best way is using object map.
```
const specificKeyNameMap = {
  67: "Backspace",
  66:  "Enter",
  61:  "Tab",
  19:  "ArrowUp"
  ...
}

const keyName = specificKeyNameMap[keyCode] || unicodeChar
```

I guess you can try https://www.npmjs.com/package/keycode library for this, I am not sure whether android keycode and js keycode the same, but maybe it will help.

To be honest, this particular functionality is not really relevant to this library. I would say that your case where we need a specific name for a pressed key is not common, and can be covered with an additional library.

You can handle `ctrl+F` by getting information from `isCtrlPressed && keyCode === 70`. 
Regarding `ESC` handling, I am not sure if it possible to handle `ESC`, becouse system handle this and will hide the app.

Feel free to share ideas or ask for help or features, it could help with understanding what can be usefull or what can be added to improve the lib)

**Comment by stephane-r** [comment]
You totally right. Object map is the best.

Thank you for all information (and for `ESC`). I'm going to implement your library on my app with a lot of keyboard navigation :) This issue can be closed.

**Comment by ArturKalach** [comment]
Honestly, I have no idea about ê, ë, I will check it a little bit later, I guess it shouldn't be a problem because unicode should recognize this symbols.
I think I just need to switch lang to any with these symbols and check.

You can contact me on email, and share the idea. I mean, this library is focused on handing external keyboard presses on specific component, but it seems that you need more specific one, or maybe even https://github.com/kevinejohn/react-native-keyevent.

I emplemented this lib for handling long press on specifc components, and helping with any modifying keys. For example when you need select a chat message and call a menu. 

I guess collaboration, can be interesting for me, and if you ready to share the idea or requirements for features, we can think about a new lib for that.

**Comment by ArturKalach** [comment]
Hello @stephane-r,
I hope you found the solution for your app, and resolved all issues. If you have any updates or needs I would be glad if you share them with us) 

Otherwise I am going to close this issue in some weeks.

BTW: I am working on integration gampads and controllers, and probably will try to add another library for a global keyboard listening. It's complex, and could take a lot of time, but I will try to inform you when I will have any updates.
