### ISSUE TITLE
TextInput inside ExternalKeyboardView not receiving key events

### ISSUE THREAD

**Issue by mrpoodestump** [ArturKalach/react-native-external-keyboard#26]
I have a modal with a TextInput inside an ExternalKeyboardView. I'm unable to type in the textInput, should this be working or is this a known issue. 

Thanks a bunch!

**Comment by ArturKalach** [comment]
Dear @mrpoodestump,
Thank you for reporting an issue, it really hello is to improve the library.

I will try to verify and fix it in some days, but could you specify a platform, react-native version and whether new arch is enabled or not. I would also appreciate if you could share an example of usage. 

It's known that Android has an issue with TextInput, but considering specification of modal using, it seems that it relates to the lib.

Sorry for inconveniences and waiting.
Regards,

Artur Kalach

**Comment by ArturKalach** [comment]
Hello @mrpoodestump,
My sincere apologies for the delay in getting back to you. I am currently investigating the issue and have found several problems with TextInput. After the latest changes in handling key presses, TextInput on iOS has stopped working due to overriding key handling behavior. I am planning to fix it this week (I will do my best for this).

On the Android side, React Native originally had a couple of issues, including: https://github.com/facebook/react-native/issues/31820

I have some ideas for fixing this, but it may take more time, and there may be unsolvable problems regarding the native implementation of TextInput."

**Comment by ArturKalach** [comment]
Hello @mrpoodestump,

I hope this message finds you well.
I've finished implementing a workaround for TextInput, and it can now be tested with[npmjs.com/package/react-native-external-keyboard/v/0.3.0-rc.](https://www.npmjs.com/package/react-native-external-keyboard/v/0.3.0-rc).

It has a really interesting implementation from the native side, and I would like to check it in different versions of React Native first to ensure that it will work with the latest versions without any issues.

Thank you for your patience, and I would greatly appreciate any feedback.

**Comment by ArturKalach** [comment]
Hello @mrpoodestump,
I have release the `0.3.0` version https://github.com/ArturKalach/react-native-external-keyboard/releases/tag/v0.3.0
This vesrion contains a solution for TextInput focusability.

In case of any questions or issues fill free to text or create an issue.

Regarda,
Artur Kalach

**Comment by mrpoodestump** [comment]
Hey thanks a bunch Artur, I plan on revisiting this in the future, thanks for looking into it!
