### ISSUE TITLE
Detecting Shift+Enter

### ISSUE THREAD

**Issue by aimachinedream** [ArturKalach/react-native-external-keyboard#50]
Was hoping I could use this package to detect shift+enter on an external keyboard on iOS.  (Standard way most chat apps work to submit text)

I can't find a way to do it though as KeyboardExtendedInput does not have an OnKeyKeyDownPress event and while I can get the event with KeyboardExtendedVIew, I have not managed to get it to work with TextInput.  It just absorbs all events.

**Comment by ArturKalach** [comment]
Hello @aimachinedream,

I tested some chat apps on iOS and understand what you have been looking for. I will try to find a solution and share it as soon as possible; I hope it won't take a lot of time and effort.

Additionally, there could be a problem with the input submission logic on iOS and Android, because they are different for the same application on different platforms. This could take some time to align the behavior between the platforms.


Regarding `KeyboardExtendedView`, it has been designed to improve the focus behavior of views and pressable elements. `KeyboardExtendedInput` was added to fix issues with keyboard focus on Android for the TextInput. This means that we don't expect to listen for actions from TextInput via KeyboardExtendedView, because TextInput is already a tool for listening to key presses.

**Comment by ArturKalach** [comment]
Hello @aimachinedream,

Sorry, it took more time than expected, but `onSubmitEditing` handling for multiline `TextInput`(`KeyboardExtendedInput`) has been added in `0.4.1-rc`. After testing, I will release a new version.

Regards,
Artur Kalach

**Comment by ArturKalach** [comment]
Hello @aimachinedream,

I have tested the 0.4.1-rc version, and after making some updates to the typings, the 0.4.1 version has been released.
Could you check if this resolves your issue and close it if it does?

Thank you for your patience.
Regards,
Artur Kalach

**Comment by ArturKalach** [comment]
The feature was added in version 0.4.1. 
Since there have been no further issues or updates on this page, I am closing the issue.
