### ISSUE TITLE
Working on iPad but not iPhone

### ISSUE THREAD

**Issue by bryanmylee** [ArturKalach/react-native-external-keyboard#54]
I've installed this project on a simulated iPhone 15 Pro and an iPad Pro.

On the iPad, focus is handled and key down/ups are reported.

On the iPhone, no focus events are ever triggered and no key down/ups are ever reported.

I'm not sure why there is a discrepancy. I've made sure that I'm running the exact same build of my project on both devices.

**Comment by Rananjaya** [comment]
The same issue persists. Previously, key down/up events were working on one of my Android devices, but they are no longer functioning

**Comment by ArturKalach** [comment]
Dear @bryanmylee,

I have tested the example on iOS and the iPad simulator and can confirm that simulators demonstrate different behavior compared to a real iPhone device. Unfortunately, I don't have real iPad or Apple TV devices to test all features. However, the iOS API should be identical across devices.

Could I ask you to test the project on real devices and share your experience?
This could help us determine whether the issue is specific to the simulator or if there are other causes.

**Comment by bryanmylee** [comment]
Hi @ArturKalach, I've been unable to reproduce this on actual devices. While it does hinder simulator testing, it's not a dealbreaker. Thanks again for the investigation, but I'll close the issue for now.
